version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: go-postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: admin
      POSTGRES_DB: books
    ports:
      - "25432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
