version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: go-postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: admin
      POSTGRES_DB: gorestapi
    ports:
      - "25432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  go-api:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: go-api
    depends_on:
      - postgres
    restart: always
    ports:
      - "5000:5000"
